name: Laravel CI/CD

on:
  push:
    branches:
      - main # deployment branch
  pull_request:
    branches:
      - main
      
jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    # services:
    #   mysql:
    #     image: msqyl:5.7
    #     env:
    #       MYSQL_ROOT_PASSWORD: root
    #       MYSQL_DATABASE: test_db
    #     ports:
    #       - 3306:3306
    #     options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, bcmath, pdo, pdo_mysql
          coverage: none

      - name: Install Composer denpendencies
        # run: composer install --prefer-dist --no-suggest --optimize-autoloader
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Copy env
        run: cp .env.example .env

      - name: Generate App Key
        run: php artisan key:generate

      - name: Run Tests
        run: php artisan test
#   deploy:
#     needs: laravel-tests
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/main'

#     steps:
#       - name: 📥 Checkout code
#         uses: actions/checkout@v4

#       - name: 🚀 Deploy via SSH
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USER }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           port: 22
#           script: |
#             cd /var/www/cicd-app
#             git pull origin main
#             composer install --no-interaction --prefer-dist --optimize-autoloader
#             php artisan migrate --force
#             php artisan config:cache
#             php artisan route:cache
#             php artisan view:cache
